# Generated by Django 4.1.13 on 2024-08-21 17:47

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_flat', models.CharField(blank=True, max_length=50, null=True)),
                ('mrp', models.CharField(blank=True, max_length=50, null=True)),
                ('inclusive_taxes', models.CharField(blank=True, max_length=50, null=True)),
                ('selected_color', models.CharField(blank=True, max_length=255, null=True)),
                ('sizes', djongo.models.fields.JSONField(blank=True, null=True)),
                ('available_skus', djongo.models.fields.JSONField(blank=True, null=True)),
                ('fit', models.CharField(blank=True, max_length=255, null=True)),
                ('fabric', models.CharField(blank=True, max_length=255, null=True)),
                ('neck', models.CharField(blank=True, max_length=255, null=True)),
                ('sleeve', models.CharField(blank=True, max_length=255, null=True)),
                ('pattern', models.CharField(blank=True, max_length=255, null=True)),
                ('length', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('wash_care', models.CharField(blank=True, max_length=255, null=True)),
                ('please_note', models.CharField(blank=True, max_length=255, null=True)),
                ('features', djongo.models.fields.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
    ]
